version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Use Node.js version 14
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip -r function.zip .

  post_build:
    commands:
      - echo "Deploying to AWS Lambda..."
      - aws lambda update-function-code --function-name dk-lambda-github-action --zip-file fileb://function.zip --region $AWS_REGION

env:
  variables:
    AWS_REGION: "us-east-1"  # Replace with your AWS Region
  parameter-store:
    AWS_ACCESS_KEY_ID: "/codebuild/aws_access_key_id"  # Replace with the secret name for access key in Secrets Manager
    AWS_SECRET_ACCESS_KEY: "/codebuild/aws_secret_access_key"  # Replace with the secret name for secret key in Secrets Manager
